import { InputTypes } from './constants';

export const InputKey = Object.freeze({
  ADDRESS_LINE_1: 'addressLine1',
  ADDRESS_LINE_2: 'addressLine2',
  CATEGORY: 'category',
  CITY: 'city',
  DESCRIPTION: 'description',
  EMAIL: 'email',
  IMAGE_FILENAME: 'imageFilename',
  NAME_FIRST: 'nameFirst',
  NAME_LAST: 'nameLast',
  PASSWORD_CONFIRM: 'confirmPassword',
  PASSWORD_CURRENT: 'passwordCurrent',
  PASSWORD_NEW: 'passwordNew',
  PRODUCT_NAME: 'name',
  ORIGIN_COUNTRY: 'originCountry',
  PACKAGE_QUANTITY: 'packageQuantity',
  PHONE: 'phone',
  POSTAL_CODE: 'postalCode',
  PRICE_CENTS: 'priceCents',
  PROVINCE_CODE: 'provinceCode',
  SALE_UNIT: 'saleUnit',
});

const Input = Object.freeze({
  [InputKey.ADDRESS_LINE_1]: {
    name: InputKey.ADDRESS_LINE_1,
    type: InputTypes.TEXT,
    as: InputTypes.INPUT,
    placeholder: `street address`,
    autoComplete: 'address-line1',
  },
  [InputKey.ADDRESS_LINE_2]: {
    name: InputKey.ADDRESS_LINE_2,
    type: InputTypes.TEXT,
    as: InputTypes.INPUT,
    placeholder: `unit, building, etc. (optional)`,
    autoComplete: 'address-line2',
  },
  [InputKey.CATEGORY]: {
    name: InputKey.CATEGORY,
    type: null,
    as: InputTypes.SELECT,
    placeholder: null,
    autoComplete: 'off',
  },
  [InputKey.CITY]: {
    name: InputKey.CITY,
    type: InputTypes.TEXT,
    as: InputTypes.INPUT,
    placeholder: `city`,
    autoComplete: 'address-level2',
  },
  [InputKey.DESCRIPTION]: {
    name: InputKey.DESCRIPTION,
    type: InputTypes.TEXT,
    as: InputTypes.TEXTAREA,
    placeholder: `write your description here...`,
    autoComplete: 'off',
  },
  [InputKey.EMAIL]: {
    name: InputKey.EMAIL,
    type: InputTypes.EMAIL,
    as: InputTypes.INPUT,
    placeholder: `email address`,
    autoComplete: 'email',
  },
  [InputKey.IMAGE_FILENAME]: {
    name: InputKey.IMAGE_FILENAME,
    type: InputTypes.TEXT,
    as: InputTypes.INPUT,
    placeholder: `image URL`,
    autoComplete: 'off',
  },
  [InputKey.NAME_FIRST]: {
    name: InputKey.NAME_FIRST,
    type: InputTypes.TEXT,
    as: InputTypes.INPUT,
    placeholder: `first name`,
    autoComplete: 'given-name',
  },
  [InputKey.NAME_LAST]: {
    name: InputKey.NAME_LAST,
    type: InputTypes.TEXT,
    as: InputTypes.INPUT,
    placeholder: `last name`,
    autoComplete: 'family-name',
  },
  [InputKey.ORIGIN_COUNTRY]: {
    name: InputKey.ORIGIN_COUNTRY,
    type: InputTypes.TEXT,
    as: InputTypes.INPUT,
    placeholder: `country of origin`,
    autoComplete: 'off',
  },
  [InputKey.PACKAGE_QUANTITY]: {
    name: InputKey.PACKAGE_QUANTITY,
    type: InputTypes.TEXT,
    as: InputTypes.INPUT,
    placeholder: `package quantity`,
    autoComplete: 'off',
  },
  [InputKey.PASSWORD_CONFIRM]: {
    name: InputKey.PASSWORD_CONFIRM,
    type: InputTypes.PASSWORD,
    as: InputTypes.INPUT,
    placeholder: `confirm new password`,
    autoComplete: 'new-password',
  },
  [InputKey.PASSWORD_CURRENT]: {
    name: InputKey.PASSWORD_CURRENT,
    type: InputTypes.PASSWORD,
    as: InputTypes.INPUT,
    placeholder: `current password`,
    autoComplete: 'current-password',
  },
  [InputKey.PASSWORD_NEW]: {
    name: InputKey.PASSWORD_NEW,
    type: InputTypes.PASSWORD,
    as: InputTypes.INPUT,
    placeholder: `new password`,
    autoComplete: 'new-password',
  },
  [InputKey.PHONE]: {
    name: InputKey.PHONE,
    type: InputTypes.PHONE,
    as: InputTypes.INPUT,
    placeholder: `telephone number`,
    autoComplete: 'tel',
  },
  [InputKey.POSTAL_CODE]: {
    name: InputKey.POSTAL_CODE,
    type: InputTypes.TEXT,
    as: InputTypes.INPUT,
    placeholder: `postal code`,
    autoComplete: 'postal-code',
  },
  [InputKey.PRICE_CENTS]: {
    name: InputKey.PRICE_CENTS,
    type: InputTypes.TEXT,
    as: InputTypes.INPUT,
    placeholder: `price`,
    autoComplete: 'off',
  },
  [InputKey.PRODUCT_NAME]: {
    name: InputKey.PRODUCT_NAME,
    type: InputTypes.TEXT,
    as: InputTypes.INPUT,
    placeholder: `product name`,
    autoComplete: 'off',
  },
  [InputKey.PROVINCE_CODE]: {
    name: InputKey.PROVINCE_CODE,
    type: null,
    as: InputTypes.SELECT,
    placeholder: null,
    autoComplete: 'address-level1',
  },
  [InputKey.SALE_UNIT]: {
    name: InputKey.SALE_UNIT,
    type: InputTypes.TEXT,
    as: InputTypes.INPUT,
    placeholder: `sold by (e.g., each, bottle, bag)`,
    autoComplete: 'off',
  },
});

export default Input;
